
export const topicLabels = {
    "#analysis": "Analysis",
    "#entertainment": "Entertainment",
    "#immortality": "Immortality",
    "#exact_reproduction": "Exact Reproduction",
    "#distinction_from_mechanical": "Distinction from Mechanical",
    "#personality": "Personality",
    "#touch_of_a_button": "Touch of a Button",
    "#virtual_presence": "Virtual Presence",
    "#soulfulness": "Soulfulness",
    "#repeatability": "Repeatability",
    "#miracle": "Miracle",
    "#technical_invention": "Technical Invention",
    "#unreached_ideal": "Ideal Instrument",
    "#educational_use": "Educational Use",
    "#analogy_to_photography": "Analogy to Photography",
    "#home": "Home",
    "#affordability": "Affordability",
    "#sitting_woman": "Sitting Woman",
    "#analogy_to_phonograph": "Analogy to Phonograph",
    "#listening": "Revelled Listening",
    "#immediate_recognizability": "Immediate Recognizability",
    "#phantom_body": "Phantom Body",
    "#suit_every_mood": "Suit every Mood",
    "#invisibility": "Invisibility",
    "#secret": "Secret"
} as { [index: string]: string }
