name: Build & deploy Gatsby to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # make the built-in token available as GH_TOKEN
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # we’ll reconfigure origin ourselves, so disable the default creds
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Configure Git & remote URL
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin \
            https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

      - name: Build & deploy
        run: npm run deploy
        working-directory: frontend
